# Steps followed from the following Link:

https://nsrdb.nrel.gov/data-sets/api-instructions.html

# Important Sites:

NSRDB Website: https://nsrdb.nrel.gov

Get NSRDB API Key: https://developer.nrel.gov/signup/

Register to use SAM: https://sam.nrel.gov

Download the SAM Software Development Kit (SDK): https://sam.nrel.gov/sdk

NSRDB download instructions using API: https://developer.nrel.gov.docs/solar/nsrdb/

# Request and API Key and fill out your info here:

In [27]:
api_user = 'naroman2@asu.edu'
api_key = 'xvwm5lypqAqWSxnwdny7IzPfrkHKfqg2gDFDV9nk'
api_key = 'xvwm5lypqAqWSxnwdny7IzPfrkHKfqg2gDFDV9nk'

# Neccessary Python Packages (pip install if you dont have them)

In [17]:
import pandas as pd
import numpy as np
import sys, os
from IPython.display import display
import requests
import io

# 1. Request Data From NSRDB using Python API

In [23]:
# Declare all variables as strings. Spaces must be replaced with '+', i.e., change 'John Smith' to 'John+Smith'.
# Define the lat, long of the location and the year (This data will be grabbed by a google maps embed on our gui)
lat, lon, year = 41.425098, -81.461236, 2010

# Set the attributes to extract (e.g., dhi, ghi, etc.), separated by commas.
attributes = 'ghi,dhi,dni,wind_speed,air_temperature,solar_zenith_angle'

# Set leap year to true or false. True will return leap day data if present, false will not.
leap_year = 'false'

# Set time interval in minutes, i.e., '30' is half hour intervals. Valid intervals are 30 & 60.
interval = '60'

# Specify Coordinated Universal Time (UTC), 'true' will use UTC, 'false' will use the local time zone of the data.
# NOTE: In order to use the NSRDB data in SAM, you must specify UTC as 'false'. SAM requires the data to be in the
# local time zone.
utc = 'false'

# Your full name, use '+' instead of spaces.
your_name = 'Nicolas+Romano'

# Your reason for using the NSRDB.
reason_for_use = 'beta+testing'
# Your affiliation
your_affiliation = 'Arizona+State+University'

# Your email address
your_email = 'naroman2@asu.edu'
# Please join our mailing list so we can keep you up-to-date on new developments.
mailing_list = 'true'

# Declare url string
url = 'https://developer.nrel.gov/api/solar/nsrdb_psm3_download.csv?wkt=POINT({lon}%20{lat})&names={year}&leap_day={leap}&interval={interval}&utc={utc}&full_name={name}&email={email}&affiliation={affiliation}&mailing_list={mailing_list}&reason={reason}&api_key={api}&attributes={attr}'.format(year=year, lat=lat, lon=lon, leap=leap_year, interval=interval, utc=utc, name=your_name, email=api_user, mailing_list=mailing_list, affiliation=your_affiliation, reason=reason_for_use, api=api_key, attr=attributes)

# Return just the first 2 lines to get metadata: (didnt work for me)
# info = pd.read_csv(url, nrows=1)
df = requests.get(url).content
df = pd.read_csv(io.StringIO(df.decode('utf-8')))

# See metadata for specified properties, e.g., timezone and elevation
timezone, elevation = df['Local Time Zone'], df['Elevation']

# 2. Print out data:

In [30]:
# Printing data table with first 24 hours:
df.head(24)

,Source,Location ID,City,State,Country,Latitude,Longitude,Time Zone,Elevation,Local Time Zone,...,Cloud Type 11,Cloud Type 12,Fill Flag 0,Fill Flag 1,Fill Flag 2,Fill Flag 3,Fill Flag 4,Fill Flag 5,Surface Albedo Units,Version
0,NSRDB,1031109,-,-,-,41.41,-81.46,-5,351,-5,...,Dust,Smoke,NaN,Missing Image,Low Irradiance,Exceeds Clearsky,Missing CLoud Properties,Rayleigh Violation,NaN,3.0.6
1,Year,Month,Day,Hour,Minute,GHI,DHI,DNI,Wind Speed,Temperature,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2010,1,1,0,30,0,0,0,1.4000000000000001,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2010,1,1,1,30,0,0,0,1.5,-1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2010,1,1,2,30,0,0,0,1.7000000000000002,-1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2010,1,1,3,30,0,0,0,1.8,-2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2010,1,1,4,30,0,0,0,1.8,-3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2010,1,1,5,30,0,0,0,1.9000000000000001,-4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2010,1,1,6,30,0,0,0,2,-4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2010,1,1,7,30,0,0,0,1.9000000000000001,-5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2010,1,1,8,30,6,6,0,2,-4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,2010,1,1,9,30,25,25,0,2.1,-4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,2010,1,1,10,30,50,50,0,2.2,-3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,2010,1,1,11,30,55,55,0,2.2,-3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,2010,1,1,12,30,46,46,0,2.4000000000000004,-3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,2010,1,1,13,30,39,39,0,2.5,-3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,2010,1,1,14,30,39,39,0,2.4000000000000004,-3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,2010,1,1,15,30,41,41,0,2.3000000000000003,-4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,2010,1,1,16,30,11,11,0,2.2,-4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,2010,1,1,17,30,0,0,0,2.1,-5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,2010,1,1,18,30,0,0,0,2.1,-5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,2010,1,1,19,30,0,0,0,2.1,-5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,2010,1,1,20,30,0,0,0,2.1,-5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,2010,1,1,21,30,0,0,0,2.1,-6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN